services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pergamum_app
    ports:
      - "5161:5161"
    volumes:
      - .:/app
      - /app/node_modules
    # Remove MONGO_URL since you're not connecting to MongoDB yet
    # environment:
    #   - MONGO_URL=mongodb://pergamum_db:27017/pergamum

# Removed the db service since you're not using MongoDB now

# volumes:
#   pergamum_mongodb_data:  # Removed as there's no database
