services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pergamum_app
    ports:
      - "5161:5001"  # CHANGED: Updated port to avoid conflict
    volumes:
      - .:/app
      - /app/node_modules
    # CHANGED: Mongo env temporarily removed
    # environment:
    #   - MONGO_URL=mongodb://pergamum_db:27017/pergamum
    # CHANGED: Mongo dependency removed
    # depends_on:
    #   - db

  # db:
  #   image: mongo:5.0
  #   container_name: pergamum_db
  #   ports:
  #     - "27018:27017"
  #   volumes:
  #     - pergamum_mongodb_data:/data/db

# volumes:
#   pergamum_mongodb_data:
